Repository YAPP-admin/attendance-android, pull requests merged in 2024-01, with the labels that each got.

#327 [Feat] 출결 이슈 다이얼로그, 보고 리스트 카드 구현
  common/src/main/java/com/yapp/common/util/Spacer.kt
  common/src/main/java/com/yapp/common/util/runIf.kt
  common/src/main/java/com/yapp/common/yds/YDSButtons.kt
  presentation/src/main/java/com/yapp/presentation/ui/admin/management/components/AttendanceReportListItem.kt
  presentation/src/main/java/com/yapp/presentation/ui/admin/management/components/attendanceTypeButton/AttendanceTypeButton.kt
  presentation/src/main/java/com/yapp/presentation/ui/admin/management/components/dialog/AttendanceIssueDialog.kt
  presentation/src/main/res/values/strings.xml
Labels: 🔨 만듭시다

#329 feat: 임시 세션 생성 화면 구현
  app/src/main/java/com/yapp/attendance/di/DataModule.kt
  data/build.gradle.kts
  data/src/main/java/com/yapp/data/datasource/SessionRemoteDataSource.kt
  data/src/main/java/com/yapp/data/datasource/SessionRemoteDataSourceImpl.kt
  data/src/main/java/com/yapp/data/model/SessionEntity.kt
  data/src/main/java/com/yapp/data/model/TeamEntity.kt
  data/src/main/java/com/yapp/data/repository/SessionRepositoryImpl.kt
  data/src/main/java/com/yapp/data/util/FireStoreReference.kt
  domain/src/main/java/com/yapp/domain/model/Session.kt
  domain/src/main/java/com/yapp/domain/model/types/NeedToAttendType.kt
  domain/src/main/java/com/yapp/domain/repository/SessionRepository.kt
  domain/src/main/java/com/yapp/domain/usecases/CheckQrAuthTimeUseCase.kt
  domain/src/main/java/com/yapp/domain/usecases/GetMemberAttendanceListUseCase.kt
  domain/src/main/java/com/yapp/domain/usecases/GetSessionListUseCase.kt
  domain/src/main/java/com/yapp/domain/usecases/GetUpcomingSessionUseCase.kt
  domain/src/main/java/com/yapp/domain/usecases/MarkAttendanceUseCase.kt
  domain/src/main/java/com/yapp/domain/usecases/SetSessionUseCase.kt
  domain/src/main/java/com/yapp/domain/usecases/SignUpMemberUseCase.kt
  presentation/src/main/java/com/yapp/presentation/ui/AttendanceScreen.kt
  presentation/src/main/java/com/yapp/presentation/ui/admin/createsession/CreateSession.kt
  presentation/src/main/java/com/yapp/presentation/ui/admin/createsession/CreateSessionContract.kt
  presentation/src/main/java/com/yapp/presentation/ui/admin/createsession/CreateSessionDateWriterDialog.kt
  presentation/src/main/java/com/yapp/presentation/ui/admin/createsession/CreateSessionDateWriterDialogState.kt
  presentation/src/main/java/com/yapp/presentation/ui/admin/createsession/CreateSessionViewModel.kt
  presentation/src/main/java/com/yapp/presentation/ui/admin/main/AdminMain.kt
  presentation/src/main/java/com/yapp/presentation/ui/admin/main/AdminMainContract.kt
  presentation/src/main/java/com/yapp/presentation/ui/admin/main/AdminMainViewModel.kt
  presentation/src/main/java/com/yapp/presentation/ui/member/score/MemberScore.kt
  presentation/src/main/java/com/yapp/presentation/ui/member/score/MemberScoreViewModel.kt
  presentation/src/main/java/com/yapp/presentation/ui/member/score/detail/SessionDetail.kt
  presentation/src/main/java/com/yapp/presentation/ui/member/score/detail/SessionDetailViewModel.kt
  presentation/src/main/java/com/yapp/presentation/ui/member/signup/password/Password.kt
  presentation/src/main/java/com/yapp/presentation/ui/member/todaysession/TodaySession.kt
  presentation/src/main/java/com/yapp/presentation/ui/member/todaysession/TodaySessionViewModel.kt
  presentation/src/main/java/com/yapp/presentation/util/attendance/AttendanceCheck.kt
  presentation/src/main/res/values/strings.xml
Labels: 🔨 만듭시다

#335 fix: 세션 유닛 테스트 수정
  data/src/test/java/com/yapp/data/ExampleUnitTest.kt
Labels: 😵 고칩시다

#333 refactor: 공통 다이얼로그 세분화
  common/src/main/java/com/yapp/common/yds/YDSPopupDialog.kt
  presentation/src/main/java/com/yapp/presentation/ui/login/Login.kt
  presentation/src/main/java/com/yapp/presentation/ui/member/todaysession/TodaySession.kt
Labels: 🪄 개선합시다
